version: '3.8'

services:
  # 后端服务
  backend:
    build: ./backend
    container_name: biorhythm-backend
    restart: always
    ports:
      - "5000:5000"
      - "8765:8765"
    environment:
      - PYTHONPATH=/app
    networks:
      - biorhythm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # 前端服务
  frontend:
    build: ./frontend
    container_name: biorhythm-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - biorhythm-network

networks:
  biorhythm-network:
    driver: bridge