version: '3'

services:
  nice-today-api:
    image: leanisssharedacr.azurecr.io/mcp/nice_today-biorhythm-api:20250801
    container_name: nice-today-api
    ports:
      - "5000:5000"  # REST API端口
      - "8765:8765"  # MCP WebSocket端口
    environment:
      - FLASK_RUN_PORT=5000
      - MCP_PORT=8765
    volumes:
      # 只映射配置文件目录
      - ./backend/config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nice-today-frontend:
    image: leanisssharedacr.azurecr.io/mcp/nice_today-biorhythm-frontend:20250801
    container_name: nice-today-frontend
    ports:
      - "3880:80"  # 修改为80端口，与前端Nginx配置一致
    depends_on:
      - nice-today-api
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./ssl:/etc/nginx/ssl:ro
        - ./frontend/config:/app/config:ro
    environment:
      - REACT_APP_BACKEND_PORT=5000
      - REACT_APP_API_DOMAIN=https://nice-mcp.leansoftx.com
      - NODE_ENV=production
      - WDS_SOCKET_PORT=0  # 解决WebSocket连接问题
    env_file:
      - .env
    restart: unless-stopped

networks:
  default:
    name: tcd-front-nginx-network
    external: true
